apiVersion: v1
kind: Pod
metadata:
  name: security
spec:
  containers:
    - name: readiness
      image: rkalluru/zs01-security
      securityContext:
        #runAsUser: 1000
        runAsNonRoot: true

