apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: index
        mountPath: /usr/share/nginx/html
  volumes:
    - name: index
      configMap:
        name: index

