apiVersion: v1
kind: Secret
metadata:
  name: sample
data:
  URL: Z29vZ2xlLmNvbQ==

---
apiVersion: v1
kind: Pod
metadata:
  name: secrets
spec:
  containers:
    - name: sample
      image: centos:7
      command:
        - sleep
        - "100000"
      env:
        - name: URL_VALUE
          valueFrom:
            secretKeyRef:
              key: URL
              name: sample
