apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - image: centos:8
      name: test-container
      command:
        - sleep
        - "100000"
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
---
